/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;


/**
 *
 * @author Diego Goncalves
 */
public class Inicio extends javax.swing.JFrame {
    
    private int amistad = 0;
    long starttime = System.currentTimeMillis();

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CargarJuego = new javax.swing.JButton();
        ComoJugar = new javax.swing.JButton();
        Creditos = new javax.swing.JButton();
        SalirJuego = new javax.swing.JButton();
        JuegoNuevo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CargarJuego.setBackground(new java.awt.Color(253, 202, 7));
        CargarJuego.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        CargarJuego.setText("CARGAR");
        CargarJuego.setBorder(null);
        CargarJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CargarJuegoActionPerformed(evt);
            }
        });
        getContentPane().add(CargarJuego, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 249, 110, 20));

        ComoJugar.setBackground(new java.awt.Color(253, 202, 7));
        ComoJugar.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        ComoJugar.setText("¿CÓMO JUGAR?");
        ComoJugar.setBorder(null);
        ComoJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComoJugarActionPerformed(evt);
            }
        });
        getContentPane().add(ComoJugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 330, 130, 30));

        Creditos.setBackground(new java.awt.Color(253, 202, 7));
        Creditos.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        Creditos.setText("CRÉDITOS");
        Creditos.setBorder(null);
        Creditos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreditosActionPerformed(evt);
            }
        });
        getContentPane().add(Creditos, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 330, -1, 30));

        SalirJuego.setBackground(new java.awt.Color(253, 202, 7));
        SalirJuego.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        SalirJuego.setText("SALIR");
        SalirJuego.setBorder(null);
        SalirJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirJuegoActionPerformed(evt);
            }
        });
        getContentPane().add(SalirJuego, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 401, -1, 30));

        JuegoNuevo.setBackground(new java.awt.Color(253, 202, 7));
        JuegoNuevo.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        JuegoNuevo.setText("JUEGO NUEVO");
        JuegoNuevo.setBorder(null);
        JuegoNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JuegoNuevoActionPerformed(evt);
            }
        });
        getContentPane().add(JuegoNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, -1, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/1.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JuegoNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JuegoNuevoActionPerformed
        MenuPrincipal menu = new MenuPrincipal();
        menu.setAmistad(getAmistad());
        menu.setStarttime(getStarttime());
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_JuegoNuevoActionPerformed

    private void SalirJuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirJuegoActionPerformed
        System.exit(WIDTH);
    }//GEN-LAST:event_SalirJuegoActionPerformed

    private void CargarJuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargarJuegoActionPerformed
        CargarJuego cargar = new CargarJuego();
        cargar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_CargarJuegoActionPerformed

    private void ComoJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComoJugarActionPerformed
        ComoJugar como = new ComoJugar();
        como.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ComoJugarActionPerformed

    private void CreditosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreditosActionPerformed
        Creditos credito = new Creditos();
        credito.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_CreditosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }
    
    /**
     * @return the amistad
     */
    public int getAmistad() {
        return amistad;
    }

    /**
     * @param amistad the amistad to set
     */
    public void setAmistad(int amistad) {
        this.amistad = amistad;
    }
    
    /**
     * @return the starttime
     */
    public long getStarttime() {
        return starttime;
    }

    /**
     * @param starttime the starttime to set
     */
    public void setStarttime(long starttime) {
        this.starttime = starttime;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CargarJuego;
    private javax.swing.JButton ComoJugar;
    private javax.swing.JButton Creditos;
    private javax.swing.JButton JuegoNuevo;
    private javax.swing.JButton SalirJuego;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

}
