/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

/**
 *
 * @author Diego Goncalves
 */
public class VerPokemon extends javax.swing.JFrame {
    
    private int watts;
    private int regalos;
    private int amistad;
    private int pokemonescogido;
    private long totaltime;
    private long starttime;

    /**
     * Creates new form VerPokemon
     */
    public VerPokemon() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Volver = new javax.swing.JButton();
        EstadoAmistad = new javax.swing.JLabel();
        Regalos = new javax.swing.JLabel();
        NumeroAmistad = new javax.swing.JLabel();
        MostrarStats = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Volver.setBackground(new java.awt.Color(253, 202, 7));
        Volver.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        Volver.setText("VOLVER");
        Volver.setBorder(null);
        Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverActionPerformed(evt);
            }
        });
        getContentPane().add(Volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 550, -1, -1));

        EstadoAmistad.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        EstadoAmistad.setText("Ver estado del pokémon:");
        getContentPane().add(EstadoAmistad, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 580, -1));

        Regalos.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        Regalos.setText("Ver lista de regalos:");
        getContentPane().add(Regalos, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 420, 460, -1));

        NumeroAmistad.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        NumeroAmistad.setText("Ver puntos de amistad:");
        getContentPane().add(NumeroAmistad, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 580, -1));

        MostrarStats.setBackground(new java.awt.Color(253, 202, 7));
        MostrarStats.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        MostrarStats.setText("MOSTRAR STATS");
        MostrarStats.setBorder(null);
        MostrarStats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarStatsActionPerformed(evt);
            }
        });
        getContentPane().add(MostrarStats, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 550, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/9.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverActionPerformed
        MenuPrincipal menu = new MenuPrincipal();
        menu.setWatts(getWatts());
        menu.setRegalos(getRegalos());
        menu.setAmistad(getAmistad());
        menu.setPokemonescogido(getPokemonescogido());
        menu.setStarttime(getStarttime());
        menu.setTotaltime(getTotaltime());
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_VolverActionPerformed

    private void MostrarStatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarStatsActionPerformed
        if (amistad > 0) {
            amistad -= 1;
        }
        NumeroAmistad.setText("Su valor actual de relación es " + amistad + " de amistad.");
        Regalos.setText("Los regalos que tiene el pokemon son ");
        if (amistad <= 2000) {
            EstadoAmistad.setText("Su estado emocional es Sigh.");
        }
        else if (amistad > 2000 && amistad <= 4000) {
            EstadoAmistad.setText("Su estado emocional es Angry.");            
        }
        else if (amistad > 4000 && amistad <= 6000) {
            EstadoAmistad.setText("Su estado emocional es Normal.");            
        }
        else if (amistad > 6000 && amistad <= 8000) {
            EstadoAmistad.setText("Su estado emocional es Happy.");            
        }
        else if (amistad > 8000) {
            EstadoAmistad.setText("Su estado emocional es Inspired.");            
        }
    }//GEN-LAST:event_MostrarStatsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VerPokemon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VerPokemon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VerPokemon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VerPokemon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VerPokemon().setVisible(true);
            }
        });
    }
    
    /**
     * @return the watts
     */
    public int getWatts() {
        return watts;
    }

    /**
     * @param watts the watts to set
     */
    public void setWatts(int watts) {
        this.watts = watts;
    }
    
    /**
     * @return the regalos
     */
    public int getRegalos() {
        return regalos;
    }

    /**
     * @param regalos the regalos to set
     */
    public void setRegalos(int regalos) {
        this.regalos = regalos;
    }
    
    /**
     * @return the amistad
     */
    public int getAmistad() {
        return amistad;
    }

    /**
     * @param amistad the amistad to set
     */
    public void setAmistad(int amistad) {
        this.amistad = amistad;
    }
    
    /**
     * @return the pokemonescogido
     */
    public int getPokemonescogido() {
        return pokemonescogido;
    }

    /**
     * @param pokemonescogido the pokemonescogido to set
     */
    public void setPokemonescogido(int pokemonescogido) {
        this.pokemonescogido = pokemonescogido;
    }
    
    /**
     * @return the starttime
     */
    public long getStarttime() {
        return starttime;
    }

    /**
     * @param starttime the starttime to set
     */
    public void setStarttime(long starttime) {
        this.starttime = starttime;
    }
    
    /**
     * @return the lasttime
     */
    public long getTotaltime() {
        return totaltime;
    }

    /**
     * @param totaltime the lasttime to set
     */
    public void setTotaltime(long totaltime) {
        this.totaltime = totaltime;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EstadoAmistad;
    private javax.swing.JButton MostrarStats;
    private javax.swing.JLabel NumeroAmistad;
    private javax.swing.JLabel Regalos;
    private javax.swing.JButton Volver;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
